#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --gpus=1
#SBATCH --partition=gpu
#SBATCH --time=04:00:00

# Execute program located in $HOME
module purge

module load 2022
module load Anaconda3/2022.05

source activate medical-imaging

srun python $HOME/pcam-stain/train.py \
    --model swin-v2-b \
    --epochs 5 \
    --transform "regular-shape-color" \
    --data-dir "data/stain" \
    --data-key "norm"
