#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --gpus=1
#SBATCH --partition=gpu
#SBATCH --time=10:00:00

# Load modules
module purge

module load 2022
module load Anaconda3/2022.05

source activate medical-imaging

# Experiment Config Example
srun python $HOME/ensemble-fusion/pcam-stain/train_fusion_ensemble.py \
    --config configs/stain_fusion.json \
    --transform base \
    --data-dir data/stain_full \
    --epochs 3
