#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --gpus=1
#SBATCH --partition=gpu
#SBATCH --time=03:00:00

# Execute program located in $HOME
module purge

module load 2022
module load Anaconda3/2022.05

source activate medical-imaging

srun python $HOME/PatchCamelyon-Medical-Imaging/trainensemble.py \
    --config configs/connected_ensemble/inception_vit.json \
    --epochs 5 \
    --transform "regular-shape-color"
